dist: trusty
os: linux
language: node_js
notifications:
  email: false
cache:
  directories:
    - "~/.npm"
    - "~/.cache"
node_js:
  - 12.16.3
install:
  - yarn install
script:
  - yarn run ci
after_success:
  - codecov
